// import { Inter } from "next/font/google";
// import "./globals.css";
// import i18nConfig from "../../../i18nConfig";
// import { dir } from "i18next";

// export function generateStaticParams() {
//   return i18nConfig.locales.map((locale) => ({ locale }));
// }

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children, params: { locale } }) {
//   return (
//     <html lang={locale} dir={dir(locale)}>
//       <body className={inter.className}>{children}</body>
//     </html>
//   );
// }


import { Inter } from "next/font/google";
import "./globals.css";
import i18nConfig from "../../../i18nConfig";
import { dir } from "i18next";

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)} className="">
      <body
        className={`${inter.className} relative bg-cover bg-center bg-fixed`}
        style={{
          backgroundImage: "url('/background.jpeg')",
          backgroundSize: "cover",
          backgroundPosition: "center",
          backgroundRepeat: "no-repeat",
        }}
      >
        {children}
      </body>
    </html>
  );
}
