import { Inter } from "next/font/google";
import "./globals.css";
import i18nConfig from "../../../i18nConfig";
import { dir } from "i18next";
import BackgroundLayout from "../components/BackgroundLayout"; // ✅ Import new wrapper

export function generateStaticParams() {
  return i18nConfig.locales.map((locale) => ({ locale }));
}

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, params: { locale } }) {
  return (
    <html lang={locale} dir={dir(locale)} className={inter.className}>
      <body className="relative">
        {/* ✅ Wrap in BackgroundLayout to control background */}
        <BackgroundLayout>{children}</BackgroundLayout>
      </body>
    </html>
  );
}
